title: My Blue Green Blog
description: A minimal blog with a blue-green theme.
baseurl: "" # leave it empty for GitHub Pages
url: "https://yourgithubusername.github.io" # Change this later
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
